[package]
name = "ggez-egui"
version = "0.2.1"
edition = "2021"
authors = ["NemuiSen <nekonya.sen@gmail.com>"]
license  = "MIT"
repository = "https://github.com/NemuiSen/ggez-egui"
keywords = ["ggez", "egui", "gui", "gamedev"]
description = "A simple implementation of egui for ggez"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.18.1"
ggez = "0.8.0-rc0"
