name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: mbrobbel/rustfmt-check@5.0.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
